export type MediaItem = {
  id: string;
  type: "video" | "podcast" | "article";
  title: string;
  description?: string;
  url: string;
  thumbnail: string;
  duration?: string;
  date?: string;
  embedUrl?: string;
};

// Original media items for main page display (3 of each type)
export const featuredMediaItems: MediaItem[] = [
  // Original 3 videos
  {
    id: "yt-1",
    type: "video",
    title: "April Armstrong on NBC-New Mexico",
    description: "April Armstrong shares 5 tips to make a new start with ease.",
    url: "https://www.youtube.com/watch?v=3iuUBIqVLo8&list=PLrGbuSJdBwUrlBcScNiAe7TRm2pvmuT_y&index=4",
    thumbnail: "https://i.ytimg.com/vi/3iuUBIqVLo8/hqdefault.jpg",
    duration: "3:13",
    date: "2018-10-11",
  },
  {
    id: "yt-2",
    type: "video",
    title: "April Armstrong on CW-Chicago",
    description: "April Armstrong shares holiday tips to help you advance your career in the new year.",
    url: "https://www.youtube.com/watch?v=ZhpC47fVhYE&list=PLrGbuSJdBwUrlBcScNiAe7TRm2pvmuT_y&index=8",
    thumbnail: "https://i.ytimg.com/vi/ZhpC47fVhYE/hqdefault.jpg",
    duration: "4:15",
    date: "2019-06-20",
  },
  {
    id: "yt-3",
    type: "video",
    title: "April Armstrong on FOX News-Virginia",
    description: "More than 30% of Americans are not happy in their jobs. This doesn't have to be you. April Armstrong gives tips to change it up in your job.",
    url: "https://www.youtube.com/watch?v=mrxzxFmU9RQ&list=PLrGbuSJdBwUrlBcScNiAe7TRm2pvmuT_y&index=1",
    thumbnail: "https://i.ytimg.com/vi/mrxzxFmU9RQ/hqdefault.jpg",
    duration: "3:51",
    date: "2018-09-15",
  },
  // Original 3 podcasts
  {
    id: "pod-1",
    type: "podcast",
    title: "Ep. 623 - The Day One Executive with April Armstrong",
    description: "Every single person has the innate ability to become a good leader, and the only thing you have to do is tap this power deep within you.",
    url: "https://podcasts.apple.com/us/podcast/ep-623-the-day-one-executive-with-april/id1290656762?i=1000597255849",
    embedUrl: "https://embed.podcasts.apple.com/us/podcast/ep-623-the-day-one-executive-with-april/id1290656762?i=1000597255849",
    thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/9c/24/a7/9c24a774-e41e-9264-1411-2b25fb11cb8d/mza_1282604419138732931.jpg/300x300bb.webp",
    duration: "36:00",
    date: "2023-01-30",
  },
  {
    id: "pod-2",
    type: "podcast",
    title: "Leading Change During a Crisis — April Armstrong",
    url: "https://podcasts.apple.com/us/podcast/leading-change-during-a-crisis-april-armstrong/id1439952788?i=1000474311042",
    embedUrl: "https://embed.podcasts.apple.com/us/podcast/leading-change-during-a-crisis-april-armstrong/id1439952788?i=1000474311042",
    thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/2a/fa/4e/2afa4e60-4f29-10dc-21cd-1fa5ef49e881/mza_10503026220572189676.png/300x300bb.webp",
    description: "Leading complex changes – especially during a crisis – requires leaders to be master balancers in that they have to manage both the human aspects of change.",
    duration: "56 min",
    date: "2020-05-12",
  },
  {
    id: "pod-3",
    type: "podcast",
    title: "April Armstrong - You Don't Have to Have Your Own Business to Be an Entrepreneur",
    description: "Have you ever thought about being your own boss and maybe you're reluctant to leap? What if you could have your cake and eat it too?",
    url: "https://music.amazon.com/podcasts/f9dd9712-098b-40b1-aa16-4d0b031dddc3/episodes/18bf578c-42b9-4eef-8862-875dfd8fd9f4/imperfect-brilliance-with-betsy-mcloughlin-april-armstrong---you-don%E2%80%99t-have-to-have-your-own-business-to-be-an-entrepreneur",
    embedUrl: "https://music.amazon.com/podcasts/f9dd9712-098b-40b1-aa16-4d0b031dddc3/episodes/18bf578c-42b9-4eef-8862-875dfd8fd9f4/imperfect-brilliance-with-betsy-mcloughlin-april-armstrong---you-don%E2%80%99t-have-to-have-your-own-business-to-be-an-entrepreneur",
    thumbnail: "https://m.media-amazon.com/images/S/dmp-catalog-images-prod/images/f9dd9712-098b-40b1-aa16-4d0b031dddc3/18bf578c-42b9-4eef-8862-875dfd8fd9f4-787604756._SX768_SY768_BL0_QL100__UX358_FMwebp_QL85_.jpg",
    duration: "56 min",
    date: "2019-11-26",
  },
  // Original 3 articles
  {
    id: "art-1",
    type: "article",
    title: "Eight Perspectives Every Executive Needs To Make Sound Decisions In A Crisis",
    description: "A practical framework of eight perspectives leaders should convene to make timely, sound decisions in a crisis.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2020/05/06/eight-perspectives-every-executive-needs-to-make-sound-decisions-in-a-crisis/",
    thumbnail: "/logos/Frobes1.png",
    date: "2020-05-06",
  },
  {
    id: "art-2",
    type: "article",
    title: "16 Ways Professionals Can Avoid Overcommitting Themselves",
    description: "Forbes Coaches Council members share practical rules and strategies to prevent overcommitment and burnout.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/08/02/16-ways-professionals-can-avoid-overcommitting-themselves/",
    thumbnail: "/logos/Forbes2.png",
    date: "2022-08-02",
  },
  {
    id: "art-3",
    type: "article",
    title: "12 Effective Ways For Managers To Get Employees Re-Engaged",
    description: "Practical tactics from Forbes Coaches Council to help managers reignite employee engagement.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/11/02/12-effective-ways-for-managers-to-get-employees-re-engaged/",
    thumbnail: "/logos/Forbes3.png",
    date: "2021-11-02",
  },
];

// All media items for the view all page
export const mediaItems: MediaItem[] = [
  {
    id: "yt-1",
    type: "video",
    title: "April Armstrong on NBC-New Mexico",
    description: "April Armstrong shares 5 tips to make a new start with ease.",
    url: "https://www.youtube.com/watch?v=3iuUBIqVLo8&list=PLrGbuSJdBwUrlBcScNiAe7TRm2pvmuT_y&index=4",
    thumbnail: "https://i.ytimg.com/vi/3iuUBIqVLo8/hqdefault.jpg",
    duration: "3:13",
    date: "2018-10-11",
  },
  {
    id: "yt-2",
    type: "video",
    title: "April Armstrong on CW-Chicago",
    description: "April Armstrong shares holiday tips to help you advance your career in the new year.",
    url: "https://www.youtube.com/watch?v=ZhpC47fVhYE&list=PLrGbuSJdBwUrlBcScNiAe7TRm2pvmuT_y&index=8",
    thumbnail: "https://i.ytimg.com/vi/ZhpC47fVhYE/hqdefault.jpg",
    duration: "4:15",
    date: "2019-06-20",
  },
  {
    id: "yt-3",
    type: "video",
    title: "April Armstrong on FOX News-Virginia",
    description: "More than 30% of Americans are not happy in their jobs. This doesn't have to be you. April Armstrong gives tips to change it up in your job.",
    url: "https://www.youtube.com/watch?v=mrxzxFmU9RQ&list=PLrGbuSJdBwUrlBcScNiAe7TRm2pvmuT_y&index=1",
    thumbnail: "https://i.ytimg.com/vi/mrxzxFmU9RQ/hqdefault.jpg",
    duration: "3:51",
    date: "2018-09-15",
  },
  {
    id: "pod-1",
    type: "podcast",
    title: "Ep. 623 - The Day One Executive with April Armstrong",
    description: "Every single person has the innate ability to become a good leader, and the only thing you have to do is tap this power deep within you.",
    url: "https://podcasts.apple.com/us/podcast/ep-623-the-day-one-executive-with-april/id1290656762?i=1000597255849",
    embedUrl: "https://embed.podcasts.apple.com/us/podcast/ep-623-the-day-one-executive-with-april/id1290656762?i=1000597255849",
    thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/9c/24/a7/9c24a774-e41e-9264-1411-2b25fb11cb8d/mza_1282604419138732931.jpg/300x300bb.webp",
    duration: "36:00",
    date: "2023-01-30",
  },
  {
    id: "pod-2",
    type: "podcast",
    title: "Leading Change During a Crisis — April Armstrong",
    url: "https://podcasts.apple.com/us/podcast/leading-change-during-a-crisis-april-armstrong/id1439952788?i=1000474311042",
    embedUrl: "https://embed.podcasts.apple.com/us/podcast/leading-change-during-a-crisis-april-armstrong/id1439952788?i=1000474311042",
    thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/2a/fa/4e/2afa4e60-4f29-10dc-21cd-1fa5ef49e881/mza_10503026220572189676.png/300x300bb.webp",
    description: "Leading complex changes – especially during a crisis – requires leaders to be master balancers in that they have to manage both the human aspects of change.",
    duration: "56 min",
    date: "2020-05-12",
  },
  {
    id: "pod-3",
    type: "podcast",
    title: "April Armstrong - You Don’t Have to Have Your Own Business to Be an Entrepreneur",
    description: "Have you ever thought about being your own boss and maybe you’re reluctant to leap? What if you could have your cake and eat it too?",
    url: "https://music.amazon.com/podcasts/f9dd9712-098b-40b1-aa16-4d0b031dddc3/episodes/18bf578c-42b9-4eef-8862-875dfd8fd9f4/imperfect-brilliance-with-betsy-mcloughlin-april-armstrong---you-don%E2%80%99t-have-to-have-your-own-business-to-be-an-entrepreneur",
    embedUrl: "https://music.amazon.com/podcasts/f9dd9712-098b-40b1-aa16-4d0b031dddc3/episodes/18bf578c-42b9-4eef-8862-875dfd8fd9f4/imperfect-brilliance-with-betsy-mcloughlin-april-armstrong---you-don%E2%80%99t-have-to-have-your-own-business-to-be-an-entrepreneur",
    thumbnail: "https://m.media-amazon.com/images/S/dmp-catalog-images-prod/images/f9dd9712-098b-40b1-aa16-4d0b031dddc3/18bf578c-42b9-4eef-8862-875dfd8fd9f4-787604756._SX768_SY768_BL0_QL100__UX358_FMwebp_QL85_.jpg",
    duration: "56 min",
    date: "2019-11-26",
  },
  {
    id: "art-1",
    type: "article",
    title: "Eight Perspectives Every Executive Needs To Make Sound Decisions In A Crisis",
    description: "A practical framework of eight perspectives leaders should convene to make timely, sound decisions in a crisis.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2020/05/06/eight-perspectives-every-executive-needs-to-make-sound-decisions-in-a-crisis/",
    thumbnail: "/logos/Frobes1.png",
    date: "2020-05-06",
  },
  {
    id: "art-2",
    type: "article",
    title: "16 Ways Professionals Can Avoid Overcommitting Themselves",
    description: "Forbes Coaches Council members share practical rules and strategies to prevent overcommitment and burnout.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/08/02/16-ways-professionals-can-avoid-overcommitting-themselves/",
    thumbnail: "/logos/Forbes2.png",
    date: "2022-08-02",
  },
  {
    id: "art-3",
    type: "article",
    title: "12 Effective Ways For Managers To Get Employees Re-Engaged",
    description: "Practical tactics from Forbes Coaches Council to help managers reignite employee engagement.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/11/02/12-effective-ways-for-managers-to-get-employees-re-engaged/",
    thumbnail: "/logos/Forbes3.png",
    date: "2021-11-02",
  },
  {
    id: "art-4",
    type: "article",
    title: "How A Better Decision Process Equals Better Decisions—And Higher Trust",
    description: "A framework for choosing the right decision-making approach to build trust and improve outcomes using the ACDC model: Authoritative, Consultative, Delegative, and Consensus.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/08/02/how-a-better-decision-process-equals-better-decisions-and-higher-trust/",
    thumbnail: "/logos/forbes4.png",
    date: "2022-08-02",
  },
  {
    id: "art-5",
    type: "article",
    title: "16 Ways For Leaders To Create A Psychologically Safe Workplace",
    description: "Forbes Coaches Council members share strategies for building workplace cultures where employees feel safe to express themselves, share ideas, and be their authentic selves.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/07/08/16-ways-for-leaders-to-create-a-psychologically-safe-workplace/",
    thumbnail: "/logos/forbes5.png",
    date: "2022-07-08",
  },
  {
    id: "art-6",
    type: "article",
    title: "14 Examples Where In-Person Communication Is Better Than Virtual At Work",
    description: "Forbes Coaches Council members explore workplace scenarios where face-to-face communication delivers better outcomes than virtual interactions, from building trust to conflict resolution.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/07/25/14-examples-where-in-person-communication-is-better-than-virtual-at-work/",
    thumbnail: "/logos/forbes6.png",
    date: "2022-07-25",
  },
  {
    id: "art-7",
    type: "article",
    title: "How More Reserved Employees Can Make Their Voices Heard",
    description: "Forbes Coaches Council members share practical strategies for introverted and quiet employees to overcome reluctance and effectively voice their valuable insights and ideas in the workplace.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/07/22/how-more-reserved-employees-can-make-their-voices-heard/",
    thumbnail: "/logos/forbes7.png",
    date: "2022-07-22",
  },
  {
    id: "art-8",
    type: "article",
    title: "15 Smart Ways For Junior Employees To Influence Change In Their Organizations",
    description: "Forbes Coaches Council members provide strategic advice for newer employees to effectively influence organizational change, from building credibility to finding the right allies and framing ideas effectively.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/05/23/15-smart-ways-for-junior-employees-to-influence-change-in-their-organizations/",
    thumbnail: "/logos/forbes8.png",
    date: "2022-05-23",
  },
  {
    id: "art-9",
    type: "article",
    title: "How To Provide Guidance Without Micromanaging",
    description: "Training Industry article exploring effective leadership strategies for providing support and guidance to team members while maintaining autonomy and avoiding micromanagement behaviors.",
    url: "https://trainingindustry.com/articles/performance-management/how-to-provide-guidance-without-micromanaging/",
    thumbnail: "/logos/forbes9.png",
    date: "2022-01-01",
  },
  {
    id: "art-10",
    type: "article",
    title: "16 Common Ways Managers Inadvertently Alienate Employees",
    description: "Forbes Coaches Council members identify frequent management behaviors that unintentionally create distance and disengagement, from failing to acknowledge high performers to micromanaging and lacking consistent appreciation.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/05/23/16-common-ways-managers-inadvertently-alienate-employees/",
    thumbnail: "/logos/forbes10.png",
    date: "2022-05-23",
  },
  {
    id: "art-11",
    type: "article",
    title: "14 Ways To Build Manager-Employee Relationships Based On Mutual Trust",
    description: "Forbes Coaches Council members share strategies for developing strong, trusting relationships between managers and employees through transparency, consistency, and authentic leadership practices.",
    url: "https://www.forbes.com/sites/forbescoachescouncil/2022/04/20/14-ways-to-build-manager-employee-relationships-based-on-mutual-trust/?sh=4845823a7a6f",
    thumbnail: "/logos/forbes11.png",
    date: "2022-04-20",
  },
  {
    id: "art-12",
    type: "article",
    title: "The Coaching Corner Blog - September 2016",
    description: "Justice Coaching Center blog post featuring insights and strategies for effective coaching and leadership development from September 2016.",
    url: "https://justicecoachingcenter.com/the-coaching-corner-blog/september-2016",
    thumbnail: "/logos/forbes12.png",
    date: "2016-09-01",
  },
  {
    id: "art-13",
    type: "article",
    title: "16 Mental Tricks To Step Out Of Your Comfort Zone",
    description: "Forbes Coaches Council members share psychological strategies and mental exercises to help individuals overcome fear and expand their boundaries, from visualization techniques to reframing comfort zones.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2022/04/12/16-mental-tricks-to-step-out-of-your-comfort-zone/",
    thumbnail: "/logos/forbes13.png",
    date: "2022-04-12",
  },
  {
    id: "art-14",
    type: "article",
    title: "11 Things To Consider When Vetting Potential Coaches For Executive Development",
    description: "Forbes Coaches Council members provide guidance on evaluating and selecting executive coaches, covering key factors such as credentials, experience, approach, and cultural fit for effective leadership development.",
    url: "https://www.forbes.com/sites/forbescoachescouncil/2021/10/29/11-things-to-consider-when-vetting-potential-coaches-for-executive-development/?sh=6426ccaa6c25",
    thumbnail: "/logos/forbes14.png",
    date: "2021-10-29",
  },
  {
    id: "art-15",
    type: "article",
    title: "Being Asked To Take On Too Much At Work: 16 Diplomatic Ways To Push Back",
    description: "Forbes Coaches Council members share diplomatic strategies for setting boundaries and managing workload, from offering alternative solutions to transparent communication about priorities and capacity.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/10/26/being-asked-to-take-on-too-much-at-work-16-diplomatic-ways-to-push-back/",
    thumbnail: "/logos/forbes15.png",
    date: "2021-10-26",
  },
  {
    id: "art-16",
    type: "article",
    title: "12 Tips To Help A Workplace Bully Change Their Ways",
    description: "Forbes Coaches Council members provide strategies for addressing workplace bullying behavior, from increasing awareness through feedback to removing reward systems that perpetuate negative interactions.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/05/28/12-tips-to-help-a-workplace-bully-change-their-ways/",
    thumbnail: "/logos/forbes16.png",
    date: "2021-05-28",
  },
  {
    id: "art-17",
    type: "article",
    title: "11 Ways Junior Employees Can Effect Change In Their Organizations",
    description: "Forbes Coaches Council members share strategies for newer employees to gain influence and make their voices heard, from building personal brands to finding small ways to contribute and add value to senior leaders.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/05/21/11-ways-junior-employees-can-effect-change-in-their-organizations/",
    thumbnail: "/logos/forbes17.png",
    date: "2021-05-21",
  },
  {
    id: "art-18",
    type: "article",
    title: "11 Smart Ways For CEOs To Handle Reports Of Bullying",
    description: "Forbes Coaches Council members provide guidance for chief executives on addressing workplace bullying reports, from investigating and documenting incidents to implementing zero-tolerance policies and 360-degree assessments.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/04/16/11-smart-ways-for-ceos-to-handle-reports-of-bullying/",
    thumbnail: "/logos/forbes18.png",
    date: "2021-04-16",
  },
  {
    id: "art-19",
    type: "article",
    title: "15 Effective And Tactful Ways To Challenge The Boss's Idea",
    description: "Forbes Coaches Council members share strategies for respectfully offering differing opinions to leaders, from asking powerful questions to building on ideas and using inclusive language to foster productive dialogue.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/01/12/15-effective-and-tactful-ways-to-challenge-the-bosss-idea/",
    thumbnail: "/logos/forbes19.png",
    date: "2021-01-12",
  },
  {
    id: "art-20",
    type: "article",
    title: "How To Negotiate Successfully: 14 Tips From Coaching Professionals",
    description: "Forbes Coaches Council members provide negotiation strategies for professionals, covering preparation, confidence building, understanding the other party's needs, and learning to tolerate discomfort for better outcomes.",
    url: "https://www.forbes.com/councils/forbescoachescouncil/2021/01/11/how-to-negotiate-successfully-14-tips-from-coaching-professionals/",
    thumbnail: "/logos/forbes20.png",
    date: "2021-01-11",
  },
  {
    id: "vid-6",
    type: "video",
    title: "April Armstrong on CBS-Sacramento",
    description: "A featured YouTube video from April Armstrong discussing executive leadership and professional development strategies.",
    url: "https://www.youtube.com/watch?v=K-lLXUpcEE0",
    thumbnail: "https://i.ytimg.com/vi/K-lLXUpcEE0/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBNkMavUxMgeVt-BMP_v44h5ccAfQ",
    date: "2021-01-01",
  },
  {
    id: "vid-7",
    type: "video",
    title: "April Armstrong on NBC-New Mexico",
    description: "A featured YouTube video from April Armstrong discussing executive leadership and professional development strategies.",
    url: "https://www.youtube.com/watch?v=vhekB69CL7c",
    thumbnail: "https://i.ytimg.com/an_webp/vhekB69CL7c/mqdefault_6s.webp?du=3000&sqp=CIW_ssYG&rs=AOn4CLCS07bpoAzG8xPvIaFqmTAT2YzxuA",
    date: "2021-01-01",
  },
  {
    id: "vid-8",
    type: "video",
    title: "April Armstrong on NBC-Louisiana",
    description: "A featured YouTube video from April Armstrong discussing executive leadership and professional development strategies.",
    url: "https://www.youtube.com/watch?v=yjXWRH2t14I",
    thumbnail: "https://i.ytimg.com/vi/yjXWRH2t14I/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLB-asrh7DO1GQ6-P_tI1fXENL_cVw",
    date: "2021-01-01",
  },
];


